server:
  port: 7100
spring:
  application:
    name: mall-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7000/eureka
zuul:
  prefix: /api #\u6DFB\u52A0\u8DEF\u7531\u524D\u7F00
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000 # \u7194\u65AD\u8D85\u65F6\u5E02\u573A

ribbon:
  ConnectTimeout: 1000 # ribbon\u8D85\u65F6\u65F6\u957F
  ReadTimeout: 3500 # ribbon\u8BFB\u53D6\u8D85\u65F6\u65F6\u957F
  MaxAutoRetries: 0 # \u5F53\u524D\u670D\u52A1\u91CD\u8BD5\u6B21\u6570
  MaxAutoRetriesNextServer: 0 # \u5207\u6362\u670D\u52A1\u91CD\u8BD5\u6B21\u6570
