server:
  port: 8001
spring:
  application:
    name: admin-service
  datasource:
    url: jdbc:mysql://localhost/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
